spring:
  application:
    name: htmlscrapper
  datasource:
    url: jdbc:mysql://localhost:3306/advertisement_scrapper?createDatabaseIfNotExist=true
    username: root
    password: Stefan0987
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
        hbm2ddl:
          auto: update
        generate_statistics: true
        jdbc:
          batch_size: 10
        order_inserts: true
        
logging:
  level:
    org:
      hibernate:
        tool:
          hbm2ddl: 'DEBUG'
      springframework:
        web: 'INFO'
        jdbc:
          core: 'DEBUG'        
        
scrapper:
  scheduling:
    cron: '0 12 * * *'
    
